In [67]:
import pandas as pd

In [68]:
import numpy as np

In [69]:
df=pd.read_csv('Downloads/job.csv')

In [91]:
df.head()

,job_id,job_title,company,location,experience_required,employment_type,salary_min,salary_max,skills,education,industry,posted_date,remote,job_description
0,JOB0001,Data Analyst,TCS,Mumbai,0-1 years,Full-time,350000,520000,Python;SQL;Excel;Power BI,B.Tech,IT Services,03-01-2026,Hybrid,Analyze business data and prepare actionable r...
1,JOB0002,Software Engineer,Infosys,Pune,1-3 years,Full-time,520000,850000,Java;Python;Git;APIs,B.E.,IT Services,04-01-2026,Yes,Develop and maintain scalable software applica...
2,JOB0003,Python Developer,Wipro,Bangalore,1-3 years,Full-time,500000,820000,Python;Django;Flask;SQL,BCA,IT Services,05-01-2026,Hybrid,Build backend applications and REST APIs.
3,JOB0004,Data Scientist,Accenture,Hyderabad,3-5 years,Full-time,850000,1350000,Python;Machine Learning;SQL;Pandas,M.Tech,Consulting,06-01-2026,Yes,Build predictive models and generate data-driv...
4,JOB0005,Java Developer,Capgemini,Chennai,1-3 years,Full-time,480000,800000,Java;Spring Boot;SQL;REST API,B.Tech,IT Services,07-01-2026,No,Develop enterprise Java applications.

In [71]:
# How many rows and columns are present in the dataset?

print(df.shape)

(401, 14)

In [72]:
# What are the columns in the dataset?
df.columns

Index(['job_id', 'job_title', 'company', 'location', 'experience_required',
       'employment_type', 'salary_min', 'salary_max', 'skills', 'education',
       'industry', 'posted_date', 'remote', 'job_description'],
      dtype='str')

In [73]:
#
df.info

<bound method DataFrame.info of       job_id               job_title    company   location  \
0    JOB0001            Data Analyst        TCS     Mumbai
1    JOB0002       Software Engineer    Infosys       Pune
2    JOB0003        Python Developer      Wipro  Bangalore
3    JOB0004          Data Scientist  Accenture  Hyderabad
4    JOB0005          Java Developer  Capgemini    Chennai
..       ...                     ...        ...        ...
396  JOB0496  Cyber Security Analyst        IBM     Mumbai
397  JOB0497  Database Administrator     Oracle    Chennai
398  JOB0498             QA Engineer  Cognizant       Pune
399  JOB0499             AI Engineer     Google  Bangalore
400  JOB0500       Marketing Analyst   Flipkart     Mumbai

    experience_required employment_type  salary_min  salary_max  \
0             0-1 years       Full-time      350000      520000
1             1-3 years       Full-time      520000      850000
2             1-3 years       Full-time      500000      820000
3             3-5 years       Full-time      850000     1350000
4             1-3 years       Full-time      480000      800000
..                  ...             ...         ...         ...
396           3-5 years       Full-time      750000     1200000
397           5-8 years       Full-time     1100000     1800000
398           1-3 years       Full-time      500000      820000
399           3-5 years       Full-time     1150000     1950000
400           1-3 years       Full-time      550000      900000

                                   skills education     industry posted_date  \
0               Python;SQL;Excel;Power BI    B.Tech  IT Services  03-01-2026
1                    Java;Python;Git;APIs      B.E.  IT Services  04-01-2026
2                 Python;Django;Flask;SQL       BCA  IT Services  05-01-2026
3      Python;Machine Learning;SQL;Pandas    M.Tech   Consulting  06-01-2026
4           Java;Spring Boot;SQL;REST API    B.Tech  IT Services  07-01-2026
..                                    ...       ...          ...         ...
396   Cybersecurity;SIEM;Networking;Linux    B.Tech      Banking  16-09-2026
397             SQL;MySQL;Oracle;Database    B.Tech      Banking  16-09-2026
398      Selenium;Testing;Java;Automation      B.E.  IT Services  16-09-2026
399           Python;AI;Deep Learning;NLP    M.Tech  IT Services  16-09-2026
400  Excel;Google Analytics;SQL;Marketing       MBA   E-Commerce  16-09-2026

     remote                                    job_description
0    Hybrid  Analyze business data and prepare actionable r...
1       Yes  Develop and maintain scalable software applica...
2    Hybrid          Build backend applications and REST APIs.
3       Yes  Build predictive models and generate data-driv...
4        No              Develop enterprise Java applications.
..      ...                                                ...
396  Hybrid                    Investigate security incidents.
397      No                       Manage enterprise databases.
398  Hybrid                 Perform quality assurance testing.
399     Yes                           Develop AI applications.
400  Hybrid               Analyze customer and marketing data.

[401 rows x 14 columns]>

In [74]:
df.describe

<bound method NDFrame.describe of       job_id               job_title    company   location  \
0    JOB0001            Data Analyst        TCS     Mumbai
1    JOB0002       Software Engineer    Infosys       Pune
2    JOB0003        Python Developer      Wipro  Bangalore
3    JOB0004          Data Scientist  Accenture  Hyderabad
4    JOB0005          Java Developer  Capgemini    Chennai
..       ...                     ...        ...        ...
396  JOB0496  Cyber Security Analyst        IBM     Mumbai
397  JOB0497  Database Administrator     Oracle    Chennai
398  JOB0498             QA Engineer  Cognizant       Pune
399  JOB0499             AI Engineer     Google  Bangalore
400  JOB0500       Marketing Analyst   Flipkart     Mumbai

    experience_required employment_type  salary_min  salary_max  \
0             0-1 years       Full-time      350000      520000
1             1-3 years       Full-time      520000      850000
2             1-3 years       Full-time      500000      820000
3             3-5 years       Full-time      850000     1350000
4             1-3 years       Full-time      480000      800000
..                  ...             ...         ...         ...
396           3-5 years       Full-time      750000     1200000
397           5-8 years       Full-time     1100000     1800000
398           1-3 years       Full-time      500000      820000
399           3-5 years       Full-time     1150000     1950000
400           1-3 years       Full-time      550000      900000

                                   skills education     industry posted_date  \
0               Python;SQL;Excel;Power BI    B.Tech  IT Services  03-01-2026
1                    Java;Python;Git;APIs      B.E.  IT Services  04-01-2026
2                 Python;Django;Flask;SQL       BCA  IT Services  05-01-2026
3      Python;Machine Learning;SQL;Pandas    M.Tech   Consulting  06-01-2026
4           Java;Spring Boot;SQL;REST API    B.Tech  IT Services  07-01-2026
..                                    ...       ...          ...         ...
396   Cybersecurity;SIEM;Networking;Linux    B.Tech      Banking  16-09-2026
397             SQL;MySQL;Oracle;Database    B.Tech      Banking  16-09-2026
398      Selenium;Testing;Java;Automation      B.E.  IT Services  16-09-2026
399           Python;AI;Deep Learning;NLP    M.Tech  IT Services  16-09-2026
400  Excel;Google Analytics;SQL;Marketing       MBA   E-Commerce  16-09-2026

     remote                                    job_description
0    Hybrid  Analyze business data and prepare actionable r...
1       Yes  Develop and maintain scalable software applica...
2    Hybrid          Build backend applications and REST APIs.
3       Yes  Build predictive models and generate data-driv...
4        No              Develop enterprise Java applications.
..      ...                                                ...
396  Hybrid                    Investigate security incidents.
397      No                       Manage enterprise databases.
398  Hybrid                 Perform quality assurance testing.
399     Yes                           Develop AI applications.
400  Hybrid               Analyze customer and marketing data.

[401 rows x 14 columns]>

In [75]:
# Are there any missing values in the dataset?
df.isnull().sum()

job_id                 0
job_title              0
company                0
location               0
experience_required    0
employment_type        0
salary_min             0
salary_max             0
skills                 0
education              0
industry               0
posted_date            0
remote                 0
job_description        0
dtype: int64

In [76]:
# Are there any duplicate records in the dataset?
df.duplicated().sum()

np.int64(0)

In [ ]:
#  Job Title Analysis

In [77]:
#  Which job titles are most in demand?

df['job_title'].value_counts()

job_title
Data Analyst                 21
Software Engineer            20
Python Developer             20
Data Scientist               20
Java Developer               20
Frontend Developer           20
Backend Developer            20
Full Stack Developer         20
Machine Learning Engineer    20
Cloud Engineer               20
DevOps Engineer              20
Business Analyst             20
Product Manager              20
Project Manager              20
UI UX Designer               20
Cyber Security Analyst       20
Database Administrator       20
QA Engineer                  20
AI Engineer                  20
Marketing Analyst            20
Name: count, dtype: int64

In [78]:
# Which job titles have the highest number of job openings?

df['job_title'].value_counts().head(10)

job_title
Data Analyst                 21
Software Engineer            20
Python Developer             20
Data Scientist               20
Java Developer               20
Frontend Developer           20
Backend Developer            20
Full Stack Developer         20
Machine Learning Engineer    20
Cloud Engineer               20
Name: count, dtype: int64

In [79]:
df['location'].value_counts().head(10)

location
Bangalore    129
Pune          85
Mumbai        72
Hyderabad     66
Chennai       33
Noida         12
Delhi          4
Name: count, dtype: int64

In [80]:
df['remote'].value_counts().head(10)

remote
Hybrid    171
Yes       160
No         70
Name: count, dtype: int64

In [81]:
df['employment_type'].value_counts().head(10)

employment_type
Full-time     394
Internship      4
Contract        3
Name: count, dtype: int64

In [82]:
df['job_title'].value_counts().head(10)

job_title
Data Analyst                 21
Software Engineer            20
Python Developer             20
Data Scientist               20
Java Developer               20
Frontend Developer           20
Backend Developer            20
Full Stack Developer         20
Machine Learning Engineer    20
Cloud Engineer               20
Name: count, dtype: int64

In [83]:
df['salary_min'].dtype

dtype('int64')

In [84]:
df['salary_max'].dtype

dtype('int64')

In [85]:
print("Minimum salary :",df['salary_min'].min())

Minimum salary : 300000

In [86]:
print("Maximum Salary :", df['salary_max'].max())

Maximum Salary : 2500000

In [92]:
print("Average Salary :", df['salary_max'].mean())

Average Salary : 1399501.246882793

In [93]:
df["average_salary"]=(df['salary_min']+df['salary_max'])

In [90]:
df.drop('average_salary',axis=1,inplace=True)

In [94]:
print("Overall average salary : ",df["average_salary"].mean())

Overall average salary :  2266783.042394015

In [95]:
df.groupby("job_title")["average_salary"].mean().sort_values(ascending=False)

job_title
Product Manager              3.705000e+06
AI Engineer                  3.475000e+06
Machine Learning Engineer    3.235000e+06
DevOps Engineer              3.210000e+06
Project Manager              3.160000e+06
Data Scientist               2.860000e+06
Cloud Engineer               2.737500e+06
Database Administrator       2.501000e+06
Full Stack Developer         2.397500e+06
Backend Developer            2.243000e+06
Java Developer               1.887000e+06
Cyber Security Analyst       1.811500e+06
Software Engineer            1.744500e+06
Frontend Developer           1.648500e+06
UI UX Designer               1.638500e+06
Business Analyst             1.548000e+06
Python Developer             1.521500e+06
Marketing Analyst            1.503500e+06
QA Engineer                  1.405000e+06
Data Analyst                 1.159048e+06
Name: average_salary, dtype: float64

In [96]:
df.groupby("experience_required")["average_salary"].mean().sort_values(ascending=False)

experience_required
5-8 years    3.471500e+06
3-5 years    2.287484e+06
1-3 years    1.432782e+06
0-1 years    8.400000e+05
Name: average_salary, dtype: float64

In [97]:
df.groupby("location")["average_salary"].mean().sort_values(ascending=False)

location
Bangalore    2.658837e+06
Hyderabad    2.538939e+06
Noida        2.352500e+06
Chennai      2.068788e+06
Pune         2.058471e+06
Mumbai       1.670694e+06
Delhi        1.665000e+06
Name: average_salary, dtype: float64

In [98]:
df.groupby("industry")["average_salary"].mean().sort_values(ascending=False)

industry
Healthcare            2.478889e+06
IT Services           2.375804e+06
E-Commerce            2.351014e+06
Banking               2.159091e+06
Consulting            2.018250e+06
Telecommunications    1.750000e+06
Retail                1.661667e+06
FinTech               1.457500e+06
Name: average_salary, dtype: float64

In [99]:
df["average_salary"].describe()

count    4.010000e+02
mean     2.266783e+06
std      8.676989e+05
min      7.500000e+05
25%      1.450000e+06
50%      2.030000e+06
75%      2.950000e+06
max      4.100000e+06
Name: average_salary, dtype: float64

In [100]:
df.head()

,job_id,job_title,company,location,experience_required,employment_type,salary_min,salary_max,skills,education,industry,posted_date,remote,job_description,average_salary
0,JOB0001,Data Analyst,TCS,Mumbai,0-1 years,Full-time,350000,520000,Python;SQL;Excel;Power BI,B.Tech,IT Services,03-01-2026,Hybrid,Analyze business data and prepare actionable r...,870000
1,JOB0002,Software Engineer,Infosys,Pune,1-3 years,Full-time,520000,850000,Java;Python;Git;APIs,B.E.,IT Services,04-01-2026,Yes,Develop and maintain scalable software applica...,1370000
2,JOB0003,Python Developer,Wipro,Bangalore,1-3 years,Full-time,500000,820000,Python;Django;Flask;SQL,BCA,IT Services,05-01-2026,Hybrid,Build backend applications and REST APIs.,1320000
3,JOB0004,Data Scientist,Accenture,Hyderabad,3-5 years,Full-time,850000,1350000,Python;Machine Learning;SQL;Pandas,M.Tech,Consulting,06-01-2026,Yes,Build predictive models and generate data-driv...,2200000
4,JOB0005,Java Developer,Capgemini,Chennai,1-3 years,Full-time,480000,800000,Java;Spring Boot;SQL;REST API,B.Tech,IT Services,07-01-2026,No,Develop enterprise Java applications.,1280000

In [61]:
np.mean(df["average_salary"])

np.float64(2266783.042394015)

In [62]:
np.median(df["average_salary"])

np.float64(2030000.0)

In [65]:
np.max(df["average_salary"])

np.int64(4100000)

In [68]:
np.min(df["average_salary"])

np.int64(750000)

In [69]:
df["salary range "]=df["salary_max"]-df['salary_min']

In [75]:
df.sort_values("salary range ",ascending=False)[["job_title","salary_min","salary_max","salary range "]].head(10)

                     job_title  salary_min  salary_max  salary range
339                AI Engineer     1550000     2450000         900000
98                 AI Engineer     1550000     2450000         900000
138                AI Engineer     1500000     2400000         900000
391            DevOps Engineer     1500000     2400000         900000
168  Machine Learning Engineer     1550000     2450000         900000
150            DevOps Engineer     1500000     2400000         900000
178                AI Engineer     1600000     2500000         900000
369  Machine Learning Engineer     1500000     2400000         900000
379                AI Engineer     1550000     2450000         900000
278                AI Engineer     1550000     2450000         900000

In [70]:
df.head()

,job_id,job_title,company,location,experience_required,employment_type,salary_min,salary_max,skills,education,industry,posted_date,remote,job_description,average_salary,salary range
0,JOB0001,Data Analyst,TCS,Mumbai,0-1 years,Full-time,350000,520000,Python;SQL;Excel;Power BI,B.Tech,IT Services,03-01-2026,Hybrid,Analyze business data and prepare actionable r...,870000,170000
1,JOB0002,Software Engineer,Infosys,Pune,1-3 years,Full-time,520000,850000,Java;Python;Git;APIs,B.E.,IT Services,04-01-2026,Yes,Develop and maintain scalable software applica...,1370000,330000
2,JOB0003,Python Developer,Wipro,Bangalore,1-3 years,Full-time,500000,820000,Python;Django;Flask;SQL,BCA,IT Services,05-01-2026,Hybrid,Build backend applications and REST APIs.,1320000,320000
3,JOB0004,Data Scientist,Accenture,Hyderabad,3-5 years,Full-time,850000,1350000,Python;Machine Learning;SQL;Pandas,M.Tech,Consulting,06-01-2026,Yes,Build predictive models and generate data-driv...,2200000,500000
4,JOB0005,Java Developer,Capgemini,Chennai,1-3 years,Full-time,480000,800000,Java;Spring Boot;SQL;REST API,B.Tech,IT Services,07-01-2026,No,Develop enterprise Java applications.,1280000,320000

In [77]:
df["skills"].head(10)

0             Python;SQL;Excel;Power BI
1                  Java;Python;Git;APIs
2               Python;Django;Flask;SQL
3    Python;Machine Learning;SQL;Pandas
4         Java;Spring Boot;SQL;REST API
5             HTML;CSS;JavaScript;React
6               Node.js;Python;APIs;SQL
7      React;Node.js;MongoDB;JavaScript
8           Python;TensorFlow;ML;Docker
9           AWS;Azure;Docker;Kubernetes
Name: skills, dtype: str

In [11]:
skills=df["skills"].str.split(",").explode()

In [80]:
skills.head(20)

0                Python;SQL;Excel;Power BI
1                     Java;Python;Git;APIs
2                  Python;Django;Flask;SQL
3       Python;Machine Learning;SQL;Pandas
4            Java;Spring Boot;SQL;REST API
5                HTML;CSS;JavaScript;React
6                  Node.js;Python;APIs;SQL
7         React;Node.js;MongoDB;JavaScript
8              Python;TensorFlow;ML;Docker
9              AWS;Azure;Docker;Kubernetes
10         Linux;Docker;Kubernetes;Jenkins
11    Excel;SQL;Power BI;Business Analysis
12        Product Strategy;Agile;Analytics
13             Agile;Scrum;Jira;Leadership
14             Figma;UI Design;UX Research
15     Cybersecurity;SIEM;Networking;Linux
16               SQL;MySQL;Oracle;Database
17        Selenium;Testing;Java;Automation
18             Python;AI;Deep Learning;NLP
19    Excel;Google Analytics;SQL;Marketing
Name: skills, dtype: str

In [12]:
skills.value_counts().head(10)

skills
Python;SQL;Excel;Power BI             21
Java;Python;Git;APIs                  20
Python;Django;Flask;SQL               20
Python;Machine Learning;SQL;Pandas    20
Java;Spring Boot;SQL;REST API         20
HTML;CSS;JavaScript;React             20
Node.js;Python;APIs;SQL               20
React;Node.js;MongoDB;JavaScript      20
Python;TensorFlow;ML;Docker           20
AWS;Azure;Docker;Kubernetes           20
Name: count, dtype: int64

In [13]:
skills=skills.str.strip()

In [14]:
skills.str.lower().eq("sql").sum()

np.int64(0)

In [6]:
df["skills"].head(10)

0             Python;SQL;Excel;Power BI
1                  Java;Python;Git;APIs
2               Python;Django;Flask;SQL
3    Python;Machine Learning;SQL;Pandas
4         Java;Spring Boot;SQL;REST API
5             HTML;CSS;JavaScript;React
6               Node.js;Python;APIs;SQL
7      React;Node.js;MongoDB;JavaScript
8           Python;TensorFlow;ML;Docker
9           AWS;Azure;Docker;Kubernetes
Name: skills, dtype: str

In [15]:
skill_percentage=(skills.value_counts()/len(df)*100).round(2)
skill_percentage.head(10)

skills
Python;SQL;Excel;Power BI             5.24
Java;Python;Git;APIs                  4.99
Python;Django;Flask;SQL               4.99
Python;Machine Learning;SQL;Pandas    4.99
Java;Spring Boot;SQL;REST API         4.99
HTML;CSS;JavaScript;React             4.99
Node.js;Python;APIs;SQL               4.99
React;Node.js;MongoDB;JavaScript      4.99
Python;TensorFlow;ML;Docker           4.99
AWS;Azure;Docker;Kubernetes           4.99
Name: count, dtype: float64

In [101]:
for skill in["sql","python","excel","power bi","tableau"]:
    count=df["skills"].str.contains(skill, case=False ,na=False).sum()
    print(skill,":",count)

sql : 161
python : 141
excel : 61
power bi : 41
tableau : 0

In [102]:
 # Remote /hybrid / on-site jobs
df["remote"].value_counts()

remote
Hybrid    171
Yes       160
No         70
Name: count, dtype: int64

In [103]:
(df["remote"].value_counts(normalize=True)*100).round(2)

remote
Hybrid    42.64
Yes       39.90
No        17.46
Name: proportion, dtype: float64

In [104]:
df["education"].value_counts().head(10)

education
B.Tech    157
MBA        80
M.Tech     60
B.E.       50
B.Des      20
MCA        19
B.Sc        9
BCA         6
Name: count, dtype: int64

In [105]:
df["industry"].value_counts().head(10)

industry
IT Services           224
E-Commerce             69
Consulting             40
Banking                33
FinTech                16
Healthcare              9
Retail                  6
Telecommunications      4
Name: count, dtype: int64

In [106]:
df.groupby("industry")["average_salary"].mean().sort_values(ascending=False).head(10)

industry
Healthcare            2.478889e+06
IT Services           2.375804e+06
E-Commerce            2.351014e+06
Banking               2.159091e+06
Consulting            2.018250e+06
Telecommunications    1.750000e+06
Retail                1.661667e+06
FinTech               1.457500e+06
Name: average_salary, dtype: float64

In [145]:
df["posted_date"]=pd.to_datetime(df["posted_date"],dayfirst=True,errors="coerce")

In [147]:
df["month"]=df["posted_date"].dt.month

In [148]:
df["month"].value_counts().sort_index()

month
1     29
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9    160
Name: count, dtype: int64

In [149]:
df["posted_date"]=pd.to_datetime(df["posted_date"],format="%d-%m-%y")

In [150]:
df["month"]=df["posted_date"].dt.month
df["month"].value_counts().sort_index()

month
1     29
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9    160
Name: count, dtype: int64

In [151]:
df["year-month"]=df["posted_date"].dt.to_period("M")
df["year-month"].value_counts().sort_index()

year-month
2026-01     29
2026-02     28
2026-03     31
2026-04     30
2026-05     31
2026-06     30
2026-07     31
2026-08     31
2026-09    160
Freq: M, Name: count, dtype: int64

In [120]:
fresher_jobs=df[df["experience_required"] == "0-1 years"]
print("fresher_jobs",
fresher_jobs.shape[0])

fresher_jobs 9

In [122]:
fresher_jobs["company"].value_counts().head(10)

company
Infosys      4
TCS          3
Accenture    1
Wipro        1
Name: count, dtype: int64

In [123]:
fresher_jobs["location"].value_counts().head(10)

location
Bangalore    3
Delhi        2
Pune         2
Mumbai       1
Hyderabad    1
Name: count, dtype: int64

In [124]:
df["experience_required"].value_counts()

experience_required
3-5 years    159
1-3 years    133
5-8 years    100
0-1 years      9
Name: count, dtype: int64

In [125]:
df["experience_required"].value_counts().head(10)

experience_required
3-5 years    159
1-3 years    133
5-8 years    100
0-1 years      9
Name: count, dtype: int64

In [126]:
df.groupby("experience_required")["average_salary"].mean().sort_values(ascending=False)

experience_required
5-8 years    3.471500e+06
3-5 years    2.287484e+06
1-3 years    1.432782e+06
0-1 years    8.400000e+05
Name: average_salary, dtype: float64

In [128]:
df["salary_range"]=df["salary_max"]-df["salary_min"]

In [130]:
df.sort_values("salary_range",ascending=False)[["job_title","salary_min","salary_max","salary_range"]].head(10)

                     job_title  salary_min  salary_max  salary_range
339                AI Engineer     1550000     2450000        900000
98                 AI Engineer     1550000     2450000        900000
138                AI Engineer     1500000     2400000        900000
391            DevOps Engineer     1500000     2400000        900000
168  Machine Learning Engineer     1550000     2450000        900000
150            DevOps Engineer     1500000     2400000        900000
178                AI Engineer     1600000     2500000        900000
369  Machine Learning Engineer     1500000     2400000        900000
379                AI Engineer     1550000     2450000        900000
278                AI Engineer     1550000     2450000        900000

In [131]:
df["salary_range"].mean()

np.float64(532219.451371571)

In [133]:
text=df["job_description"].str. lower()	.str.cat(sep=" ")

In [137]:
keyword=["SQL","python","excel","Power BI","tableau"]
for keyword in keyword:
    print(keyword," :", text.count(keyword))

SQL  : 0
python  : 15
excel  : 0
Power BI  : 0
tableau  : 0

In [138]:
np.mean(df["average_salary"])

np.float64(2266783.042394015)

In [139]:
np.median(df["average_salary"])

np.float64(2030000.0)

In [140]:
np.max(df["average_salary"])

np.int64(4100000)

In [142]:
np.min(df["average_salary"])

np.int64(750000)